// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmwcqoqzdxagxyiwzhqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtd2Nxb3F6ZHhhZ3h5aXd6aHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjM4NzcsImV4cCI6MjA2NTg5OTg3N30.-BbcrH2OEHxccProL2AfEpZDT7v3L3aGp-jzN6pydMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);