
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android SDK components
      run: |
        echo "Installing Android SDK components..."
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli@6.1.2

    - name: Verify Capacitor config
      run: |
        echo "Checking Capacitor config..."
        if [ ! -f "capacitor.config.ts" ]; then
          echo "Error: capacitor.config.ts not found"
          exit 1
        fi
        echo "Capacitor config found!"
        cat capacitor.config.ts

    - name: Clean previous build
      run: |
        echo "Cleaning previous builds..."
        rm -rf android || true
        rm -rf node_modules/.capacitor || true

    - name: Add Android platform
      run: |
        echo "Adding Android platform..."
        npx cap add android
        echo "Android platform added successfully!"
        ls -la

    - name: Sync Capacitor
      run: |
        echo "Syncing Capacitor..."
        npx cap sync android

    - name: Grant execute permissions to gradlew
      run: |
        cd android
        chmod +x ./gradlew
        echo "Gradlew permissions granted!"

    - name: Build Android APK
      run: |
        cd android
        echo "Starting Android build..."
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: android-v${{ github.run_number }}
        name: Android Release v${{ github.run_number }}
        files: android/app/build/outputs/apk/debug/app-debug.apk
        generate_release_notes: true
        body: |
          🤖 **Android APK Build Automated**
          
          📱 **Download Instructions:**
          1. Download the APK file below
          2. Transfer to your Android device
          3. Enable "Install from unknown sources" in Android settings
          4. Install the APK
          
          ⚡ **Features:**
          - Built with Capacitor
          - Hot reload enabled for development
          - Native Android capabilities
          
          🔧 **Technical Info:**
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
