
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: '33.0.0'

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Install Capacitor CLI globally
      run: npm install -g @capacitor/cli@6

    - name: Add Android platform
      run: npx cap add android

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set Java compatibility in Gradle
      run: |
        cd android
        echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
        
        # Set Java version in build.gradle
        sed -i 's/JavaVersion.VERSION_1_8/JavaVersion.VERSION_17/g' app/build.gradle
        sed -i 's/jvmTarget = "1.8"/jvmTarget = "17"/g' app/build.gradle
        
        # Ensure compileSdk and targetSdk are compatible
        sed -i 's/compileSdk [0-9]*/compileSdk 33/g' app/build.gradle
        sed -i 's/targetSdk [0-9]*/targetSdk 33/g' app/build.gradle

    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Clean before build
      run: |
        cd android
        ./gradlew clean

    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace --info
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
