
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Add Android platform
      run: npx cap add android

    - name: Copy web assets to native project
      run: npx cap copy android

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set Android SDK permissions
      run: |
        chmod +x $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || echo "SDK licenses accepted"

    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace --info
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: android-v${{ github.run_number }}
        name: Android Release v${{ github.run_number }}
        files: android/app/build/outputs/apk/debug/app-debug.apk
        generate_release_notes: true
        body: |
          🤖 Automated Android APK build
          
          📱 Download the APK file below to install on your Android device
          
          ⚠️ Make sure to enable "Install from unknown sources" in your Android settings
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
