
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.0

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || echo "SDK licenses accepted"

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Install Capacitor CLI globally
      run: npm install -g @capacitor/cli@latest

    - name: Add Android platform
      run: npx cap add android --confirm

    - name: Copy web assets to native project
      run: npx cap copy android

    - name: Update Capacitor
      run: npx cap update android

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Grant execute permissions to gradlew
      run: |
        cd android
        chmod +x ./gradlew

    - name: Clean and Build Android APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleDebug --no-daemon --stacktrace
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: android-v${{ github.run_number }}
        name: Android Release v${{ github.run_number }}
        files: android/app/build/outputs/apk/debug/app-debug.apk
        generate_release_notes: true
        body: |
          🤖 **Android APK Build Automated**
          
          📱 **Download Instructions:**
          1. Download the APK file below
          2. Transfer to your Android device
          3. Enable "Install from unknown sources" in Android settings
          4. Install the APK
          
          ⚡ **Features:**
          - Built with Capacitor
          - Hot reload enabled for development
          - Native Android capabilities
          
          🔧 **Technical Info:**
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
